import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Link from "next/link";

import "./globals.css";
import "@/components/craft/craft.css";
import { Container, Section } from "@/components/craft";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Craft Design System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}

const Header = () => {
  return (
    <Section>
      <Container>
        <h2 className="mb-2">Craft Design System</h2>
        <p className="text-muted-foreground">
          Craft is an open-source design system for building content sites and
          user interfaces. It was created by{" "}
          <a target="_blank" href="https://x.com/bridgertower">
            Bridger Tower
          </a>
          .
        </p>
        <div className="my-8 grid gap-2 craft">
          <a href="https://github.com/brijr/craft">View on GitHub</a>
          <Link href="/example">View an Article Example</Link>
        </div>
      </Container>
    </Section>
  );
};
